name: BarcodeReader.ImageSharp Build Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checking Out Code
      uses: actions/checkout@v3
      
    - name: Installing .NET Versions
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          5.0.x
          3.1.x
    
    - name: Setup MSBuild for .NET Framework Tests
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore NuGet packages for Solution
      run: dotnet restore BarcodeReader.ImageSharp.sln
      
    - name: Build Class Library Project
      run: dotnet build .\BarcodeReader.ImageSharp\BarcodeReader.ImageSharp.csproj --no-restore --framework net6.0
      
    - name: Run Tests using .NET 6
      run: dotnet test .\BarcodeReader.ImageSharp.UnitTests\BarcodeReader.ImageSharp.UnitTests.csproj --framework net6.0    
      
    - name: Run Tests using .NET 5
      run: dotnet test .\BarcodeReader.ImageSharp.UnitTests\BarcodeReader.ImageSharp.UnitTests.csproj --framework net5.0 
    
    - name: Run Tests using .NET Core 3.1
      run: dotnet test .\BarcodeReader.ImageSharp.UnitTests\BarcodeReader.ImageSharp.UnitTests.csproj --framework netcoreapp3.1
    
    - name: Run Tests using .NET Framework 4.8
      run: dotnet test .\BarcodeReader.ImageSharp.UnitTests\BarcodeReader.ImageSharp.UnitTests.csproj --framework net48
    
    - name: Run Tests using .NET Framwork 4.7.2
      run: dotnet test .\BarcodeReader.ImageSharp.UnitTests\BarcodeReader.ImageSharp.UnitTests.csproj --framework net472
 
